### ISSUE TITLE
Most logs seem incomplete

### ISSUE THREAD

**Issue by Maxzor** [rigred/sandsifter-tests#14]
Hello, I faced various crashes during 'standard' sandsifter scanning.
I ran some commands to see where the other scans ended :

#extracting archives and "organizing content".
maxzor@maxdeb970:~/sandsifter/tests/intel$for i in *; do a=\`echo $i|sed 's/.tar.xz//g'\`; tar xvf $i; mv log log_$a || mv data/log log_$a; done

#looking at the last instruction in each log.
maxzor@maxdeb970:~/sandsifter/tests/intel$for i in log*; do echo $i  \`tail -1 $i | sed 's/(\|)//g'\` | awk '{ printf "%-30s %-15s\n", $1, $7}'; done

Here is the output :
log_i7-4700mq --------------------- 660f1fff000000000000000000000000
log_i7-4790k -----------------------  660f1fff000000000000000000000000
log_intel_core2duo-P8400 ------- 660f1fff000000000000000000000000
log_intel_i3-3120M ---------------- f3dfc700000000000000000000000000
log_intel_i3-4130T ---------------- 660f8fff000000000000000000000000
log_intel_i5-2500 ------------------ 660f8fff000000000000000000000000
log_intel_i5-2540M ---------------- 660f1fff000000000000000000000000
log_intel_i5-3210m ---------------- 660f1fff000000000000000000000000
log_intel_pentium_4-630 -------- 660f8fff000000000000000000000000
log_intel_pentium-B970 --------- f3dfc700000000000000000000000000
log_intel_xeon-E3-1225-v3 ----- 660f1fff000000000000000000000000

It seems most Intel scans encounter a problem at (edit: **soon after**) instructions 660f1fff or 660f8fff000000.
Maybe it has to do with a log file limit, logs ending with 660f1fff are 200MB square.

**Comment by rigred** [comment]
This is something I have suspected for a while. We might need to blacklist this instruction. And do some testing. I will see what happens If I run just this op.

**Comment by rigred** [comment]
It's also not a filesize/sandsifter glitch. On AMD Ryzen CPU's the program generates almost a 1.4Gb log.

**Comment by Maxzor** [comment]
I need to understand sandsifter program now :) but from what I understood in blackhat talk, sandsifter was able to not get hung, working around serious instruction errors and recovering on next op.
Rerunning i5 2500 atm and approaching 660f8fff000000 again.

**Comment by rigred** [comment]
What I find interesting is how some CPU's run to further offsets than others.

**Comment by rigred** [comment]
I will do some more testing on my Pentium 630 that I have here right now. Will take a while since I have to do something else first.

You can use the -i and -e flag on the injector to set a start and stop range for the instructions.

**Comment by Maxzor** [comment]
This one i5-2500 run did not get stuck... will request pull again...
Edit : Actually it crashed and last logged ins is the same : see comments below.

**Comment by rigred** [comment]
Yeah I re-ran on the Pentium 4. 

```
#
# ./sifter.py --unk --dis --len --sync --tick -- -P1 -t -i 660f1ffd -e 660f78c2
# ./injector -P1 -t -i 660f1ffd -e 660f78c2 -t -R -0 -s 438999672
#
# insn tested: 8443080
# artf found:  6
# runtime:     00:10:29.17
# seed:        438999672
# arch:        64
# date:        2017-11-29 14:04:05
#
# cpu:
# processor     : 0
# vendor_id     : GenuineIntel
# cpu family    : 15
# model         : 4
# model name    : Intel(R) Pentium(R) 4 CPU 3.00GHz
# stepping      : 10
# microcode     : 0x4
#                               v  l  s  c
                      660f1ffd  1  4  5  2 (660f1ffd000000000000000000000000)
                      660f1ffe  1  4  5  2 (660f1ffe000000000000000000000000)
                      660f1fff  1  4  5  2 (660f1fff000000000000000000000000)
                        660f38  1  3  4  2 (660f3800000000000000000000000000)
                      660f78c0  1  4  4  2 (660f78c0000000000000000000000000)
                      660f78c1  1  4  4  2 (660f78c1000000000000000000000000)
```

**Comment by rigred** [comment]
Note the difference to previous result. There is something odd going on here.

**Comment by rigred** [comment]
Oh great now I notice that the P4 ran past the 660f1fff op. 
Which If I decode that correct is a 
`nop di`

I was looking at the wrong instruction.

**Comment by Maxzor** [comment]
Yes ofc, I am dumb, 660f1fff is the last logged instruction before crash, it is not the one that causes it.
Might need to somehow catch the **further** instruction that causes the premature scan end :)

**Comment by rigred** [comment]
I'm going to simply log every executed instruction to ramdisk now.

**Comment by rigred** [comment]
Interestingly `660f8fff000000` doesn't show up in some tests on the Ryzen CPU's.

**Comment by Maxzor** [comment]
From what I understand the injector needs some tweaking. For me it will be a great tool to learn good c, but I will not be able to "fix" this before weeks, if I ever achieve it.

**Comment by rigred** [comment]
I just managed to trigger the crash. But need to rerun it one more time since I was logging the wrong way...
Lol

**Comment by rigred** [comment]
@Maxzor try this:

sudo ./sifter.py --unk --dis --len --sync --save --tick -- -T -P1 -t -i 660fa4c412f900000000000000000000

;)

**Comment by Maxzor** [comment]
Nice, ending i5 2500 and pull request asap.
Did you understand why the error was not recovered by the injector?

**Comment by rigred** [comment]
Actually there are a number of instructions which start the failure:

660fa4c4150000000000000000000000
660fa4c415f900000000000000000000
660fa4c4180000000000000000000000
660fa4c418f900000000000000000000
660fa4c418f9f8000000000000000000
660fa4c418fa00000000000000000000
660fa4c418faf8000000000000000000

I'm still digging around as to what causes the segfault. It is CPU specific however.

**Comment by rigred** [comment]
This only works on the Pentium 4 and those CPU's which stopped at 660f8fff000000

**Comment by rigred** [comment]
Debugging this is going to suck.

**Comment by Maxzor** [comment]
:)

**Comment by Maxzor** [comment]
Do you suggest me to append the end of the scan manually to the first part?
Or, as I tend to believe, this needs to be sorted first before adding more archives?

Seed wont be the same for the two logs, no clue if that is relevant, need to understand tunnelled fuzzing vs bruteforce.

**Comment by rigred** [comment]
This needs to be resolved first. There likely could be other issues lurking further down the scan.

**Comment by Maxzor** [comment]
Quite off-topic :
Is tunneled fuzzing exhaustive? Or does it skip instructions that brute force mode would catch?
What about the millions of "unk" that defile in the sifter screen during the scan and that are not logged?

**Comment by rigred** [comment]
Tunneling is exhaustive - or rather it's supposed to be. 
The unlogged - unk are basically undefined space that's not used and isn't accepted by the decoder.

**Comment by rigred** [comment]
I have found a workaround.

Note: I still don't fully understand why this problem occurs exactly.

**Comment by rigred** [comment]
Basically need to compile the injector as static as well as -no-pie.
Fix pushed. Can rerun again :D

**Comment by rigred** [comment]
So we have to rerun the tests.... from the start.
God
Damn
It

**Comment by Maxzor** [comment]
Let s go!
Maybe clean the repo and ask the few users so far involved to rerun?

**Comment by rigred** [comment]
@Maxzor If you can please retest the B970 and see if it still completes at the f3dfc7 instruction.
I hope that the B970 and i3-3120M actually completed successfully.

**Comment by Maxzor** [comment]
Ok, damn I am killing the climate!

**Comment by rigred** [comment]
Already cleaned and branched the invalid results out.
Running tests right now.

It passes all the previously failing instructions.

**Comment by rigred** [comment]
@Maxzor actually maybe just append the `-i f3dfc7` params to continue from that and see if it progresses further on the B970.

**Comment by Maxzor** [comment]
@rigred Yes, nothing new from there

**Comment by rigred** [comment]
Ok I've gone over this and verified the i3-3120m and B970 against the Ryzen chip. and the range of most instructions match up.

These are actually complete and don't need to be retested. Yay!
