### ISSUE TITLE
Sandsifter hangs on non-pae kernel

### ISSUE THREAD

**Issue by wouterwashere** [rigred/sandsifter-tests#22]
Issue:
Sandsifter hangs on certain instructions when using a (32-bit) non-pae kernel. When not running with the -N flag on non-pae kernels, sandsifter will finish almost immediately. Turning on or off the Execute Disable Bit in the BIOS does not change this behaviour.

Workaround:
Don't run on 32-bit kernels without pae.

Footnote:
The NX bit is only available with the long mode (64 bit) and PAE page-table formats, but not x86's original 32-bit page table format.

I'll test this issue later with a CPU without actual NX bit support (Pentium 4 530) in combination with non-pae and pae-enabled kernels.

**Comment by wouterwashere** [comment]
It can be concluded that Sandsifter does not work on a 32-bit kernel without PAE support.

**Comment by rigred** [comment]
Yes. This is expected behaviour for this scenario.
I don't know of a workaround for this at the moment either aside from checking for it prior to running sandsifter.

**Comment by wouterwashere** [comment]
I don't think it is necessary to even think about a workaround. It is rather a dependency that I would like to document. Every modern Linux distribution has PAE kernels available, so I just wanted to mention it.
